// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: proto/deployments.proto

package proto_go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         bool                   `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseStatus) Reset() {
	*x = ResponseStatus{}
	mi := &file_proto_deployments_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseStatus) ProtoMessage() {}

func (x *ResponseStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deployments_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseStatus.ProtoReflect.Descriptor instead.
func (*ResponseStatus) Descriptor() ([]byte, []int) {
	return file_proto_deployments_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseStatus) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *ResponseStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateDeployRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDeployRequest) Reset() {
	*x = CreateDeployRequest{}
	mi := &file_proto_deployments_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDeployRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeployRequest) ProtoMessage() {}

func (x *CreateDeployRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deployments_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeployRequest.ProtoReflect.Descriptor instead.
func (*CreateDeployRequest) Descriptor() ([]byte, []int) {
	return file_proto_deployments_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDeployRequest) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

var File_proto_deployments_proto protoreflect.FileDescriptor

const file_proto_deployments_proto_rawDesc = "" +
	"\n" +
	"\x17proto/deployments.proto\"@\n" +
	"\x0eResponseStatus\x12\x14\n" +
	"\x05error\x18\x01 \x01(\bR\x05error\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\":\n" +
	"\x13CreateDeployRequest\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId2P\n" +
	"\x11DeploymentService\x12;\n" +
	"\x10CreateDeployment\x12\x14.CreateDeployRequest\x1a\x0f.ResponseStatus\"\x00B\fZ\n" +
	"./proto_gob\x06proto3"

var (
	file_proto_deployments_proto_rawDescOnce sync.Once
	file_proto_deployments_proto_rawDescData []byte
)

func file_proto_deployments_proto_rawDescGZIP() []byte {
	file_proto_deployments_proto_rawDescOnce.Do(func() {
		file_proto_deployments_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_deployments_proto_rawDesc), len(file_proto_deployments_proto_rawDesc)))
	})
	return file_proto_deployments_proto_rawDescData
}

var file_proto_deployments_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_deployments_proto_goTypes = []any{
	(*ResponseStatus)(nil),      // 0: ResponseStatus
	(*CreateDeployRequest)(nil), // 1: CreateDeployRequest
}
var file_proto_deployments_proto_depIdxs = []int32{
	1, // 0: DeploymentService.CreateDeployment:input_type -> CreateDeployRequest
	0, // 1: DeploymentService.CreateDeployment:output_type -> ResponseStatus
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_deployments_proto_init() }
func file_proto_deployments_proto_init() {
	if File_proto_deployments_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_deployments_proto_rawDesc), len(file_proto_deployments_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_deployments_proto_goTypes,
		DependencyIndexes: file_proto_deployments_proto_depIdxs,
		MessageInfos:      file_proto_deployments_proto_msgTypes,
	}.Build()
	File_proto_deployments_proto = out.File
	file_proto_deployments_proto_goTypes = nil
	file_proto_deployments_proto_depIdxs = nil
}
