// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: proto/deployment_node.proto

package proto_go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	CpuPerc       float64                `protobuf:"fixed64,2,opt,name=cpu_perc,json=cpuPerc,proto3" json:"cpu_perc,omitempty"`
	MemoryPerc    float64                `protobuf:"fixed64,3,opt,name=memory_perc,json=memoryPerc,proto3" json:"memory_perc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_deployment_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deployment_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_deployment_node_proto_rawDescGZIP(), []int{0}
}

func (x *HealthCheckResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HealthCheckResponse) GetCpuPerc() float64 {
	if x != nil {
		return x.CpuPerc
	}
	return 0
}

func (x *HealthCheckResponse) GetMemoryPerc() float64 {
	if x != nil {
		return x.MemoryPerc
	}
	return 0
}

type DeployAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployAppRequest) Reset() {
	*x = DeployAppRequest{}
	mi := &file_proto_deployment_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployAppRequest) ProtoMessage() {}

func (x *DeployAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deployment_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployAppRequest.ProtoReflect.Descriptor instead.
func (*DeployAppRequest) Descriptor() ([]byte, []int) {
	return file_proto_deployment_node_proto_rawDescGZIP(), []int{1}
}

func (x *DeployAppRequest) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

type DeployAppResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployAppResponse) Reset() {
	*x = DeployAppResponse{}
	mi := &file_proto_deployment_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployAppResponse) ProtoMessage() {}

func (x *DeployAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deployment_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployAppResponse.ProtoReflect.Descriptor instead.
func (*DeployAppResponse) Descriptor() ([]byte, []int) {
	return file_proto_deployment_node_proto_rawDescGZIP(), []int{2}
}

func (x *DeployAppResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

var File_proto_deployment_node_proto protoreflect.FileDescriptor

const file_proto_deployment_node_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/deployment_node.proto\x1a\x1bgoogle/protobuf/empty.proto\"j\n" +
	"\x13HealthCheckResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x19\n" +
	"\bcpu_perc\x18\x02 \x01(\x01R\acpuPerc\x12\x1f\n" +
	"\vmemory_perc\x18\x03 \x01(\x01R\n" +
	"memoryPerc\"7\n" +
	"\x10DeployAppRequest\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\"/\n" +
	"\x11DeployAppResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted2\x85\x01\n" +
	"\x0eDeploymentNode\x12=\n" +
	"\vHealthCheck\x12\x16.google.protobuf.Empty\x1a\x14.HealthCheckResponse\"\x00\x124\n" +
	"\tDeployApp\x12\x11.DeployAppRequest\x1a\x12.DeployAppResponse\"\x00B\fZ\n" +
	"./proto_gob\x06proto3"

var (
	file_proto_deployment_node_proto_rawDescOnce sync.Once
	file_proto_deployment_node_proto_rawDescData []byte
)

func file_proto_deployment_node_proto_rawDescGZIP() []byte {
	file_proto_deployment_node_proto_rawDescOnce.Do(func() {
		file_proto_deployment_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_deployment_node_proto_rawDesc), len(file_proto_deployment_node_proto_rawDesc)))
	})
	return file_proto_deployment_node_proto_rawDescData
}

var file_proto_deployment_node_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_deployment_node_proto_goTypes = []any{
	(*HealthCheckResponse)(nil), // 0: HealthCheckResponse
	(*DeployAppRequest)(nil),    // 1: DeployAppRequest
	(*DeployAppResponse)(nil),   // 2: DeployAppResponse
	(*emptypb.Empty)(nil),       // 3: google.protobuf.Empty
}
var file_proto_deployment_node_proto_depIdxs = []int32{
	3, // 0: DeploymentNode.HealthCheck:input_type -> google.protobuf.Empty
	1, // 1: DeploymentNode.DeployApp:input_type -> DeployAppRequest
	0, // 2: DeploymentNode.HealthCheck:output_type -> HealthCheckResponse
	2, // 3: DeploymentNode.DeployApp:output_type -> DeployAppResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_deployment_node_proto_init() }
func file_proto_deployment_node_proto_init() {
	if File_proto_deployment_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_deployment_node_proto_rawDesc), len(file_proto_deployment_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_deployment_node_proto_goTypes,
		DependencyIndexes: file_proto_deployment_node_proto_depIdxs,
		MessageInfos:      file_proto_deployment_node_proto_msgTypes,
	}.Build()
	File_proto_deployment_node_proto = out.File
	file_proto_deployment_node_proto_goTypes = nil
	file_proto_deployment_node_proto_depIdxs = nil
}
