# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: deployments.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'deployments.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x64\x65ployments.proto\"0\n\x0eResponseStatus\x12\r\n\x05\x65rror\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\",\n\x13\x43reateDeployRequest\x12\x15\n\rdeployment_id\x18\x01 \x01(\t2P\n\x11\x44\x65ploymentService\x12;\n\x10\x43reateDeployment\x12\x14.CreateDeployRequest\x1a\x0f.ResponseStatus\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'deployments_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESPONSESTATUS']._serialized_start=21
  _globals['_RESPONSESTATUS']._serialized_end=69
  _globals['_CREATEDEPLOYREQUEST']._serialized_start=71
  _globals['_CREATEDEPLOYREQUEST']._serialized_end=115
  _globals['_DEPLOYMENTSERVICE']._serialized_start=117
  _globals['_DEPLOYMENTSERVICE']._serialized_end=197
# @@protoc_insertion_point(module_scope)
