"""add current_deployment_id column to user applications

Revision ID: 4b55cb7e8e82
Revises: b399c284f6c7
Create Date: 2025-09-05 17:02:38.785678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b55cb7e8e82'
down_revision = 'b399c284f6c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('deployments_app_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_applications', ['app_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_deployment_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('git_repo', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_applications', schema=None) as batch_op:
        batch_op.drop_column('git_repo')
        batch_op.drop_column('current_deployment_id')

    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('deployments_app_id_fkey'), 'user_applications', ['app_id'], ['id'])

    # ### end Alembic commands ###
