"""add deployments table

Revision ID: 93e7487f983d
Revises: 0ea40e1e9513
Create Date: 2025-08-09 22:05:08.598395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93e7487f983d'
down_revision = '0ea40e1e9513'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('app_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['user_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deployments')
    # ### end Alembic commands ###
