"""add runtime column to user_applications table

Revision ID: b399c284f6c7
Revises: 93e7487f983d
Create Date: 2025-09-04 13:22:51.355582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b399c284f6c7'
down_revision = '93e7487f983d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('runtime', sa.String(length=30), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_applications', schema=None) as batch_op:
        batch_op.drop_column('runtime')

    # ### end Alembic commands ###
