"""changed created_at column type to timestamp and added updated_at column to deployments table

Revision ID: f23cf5a37266
Revises: a7ebca3bed2b
Create Date: 2025-09-05 17:44:10.314504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f23cf5a37266'
down_revision = 'a7ebca3bed2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        
    op.execute("""
        ALTER TABLE deployments
        ALTER COLUMN created_at TYPE TIMESTAMP WITHOUT TIME ZONE
        USING to_timestamp(created_at)
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
